name: Docker Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3  # Обновлённая версия

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t lab8_builder .
        docker create --name lab8_container lab8_builder
        docker start -a lab8_container || echo "Build completed"

    - name: Extract artifacts
      if: always()
      run: |
        docker cp lab8_container:/app/build_log.txt . || echo "Log not found"
        docker cp lab8_container:/app/build/lab8 . || echo "Binary not found"
        ls -la

    - name: Upload artifacts
      uses: actions/upload-artifact@v3  # Обновлённая версия
      with:
        name: build-artifacts
        path: |
          build_log.txt
          lab8
        if-no-files-found: warn

    - name: Cleanup
      run: |
        docker rm lab8_container || true
        docker rmi lab8_builder || true
